#ifndef BB_OSC_ERRORS_H
#define BB_OSC_ERRORS_H

#define BB_OSC_FW_ERROR_BASE			-1000
#define BB_OSC_NULL_PTR_ACCESS			(BB_OSC_FW_ERROR_BASE + 1)

#define BB_OSC_CMD_PROSS_ERROR_BASE		(BB_OSC_FW_ERROR_BASE + 200)
#define BB_OSC_INVALID_FLAG				(BB_OSC_CMD_PROSS_ERROR_BASE + 1)
#define BB_OSC_INVALID_SOURCE			(BB_OSC_CMD_PROSS_ERROR_BASE + 2)
#define BB_OSC_INVALID_DEST				(BB_OSC_CMD_PROSS_ERROR_BASE + 3)
#define BB_OSC_INVALID_PKT_LEN			(BB_OSC_CMD_PROSS_ERROR_BASE + 4)
#define BB_OSC_INVALID_CMD_ID			(BB_OSC_CMD_PROSS_ERROR_BASE + 5)

int BB_OSC_DisplayErrors(int iErrCode);
#endif
