#ifndef BB_OSC_ERRORS_H
#define BB_OSC_ERRORS_H

#define BB_OSC_FW_ERROR_BASE			-1000
#define BB_OSC_NULL_PTR_ACCESS			(BB_OSC_FW_ERROR_BASE + 1)

#define BB_OSC_CMD_PROSS_ERROR_BASE		(BB_OSC_FW_ERROR_BASE + 200)
#define BB_OSC_INVALID_FLAG				(BB_OSC_CMD_PROSS_ERROR_BASE + 1)
#define BB_OSC_INVALID_SOURCE			(BB_OSC_CMD_PROSS_ERROR_BASE + 2)
#define BB_OSC_INVALID_DEST				(BB_OSC_CMD_PROSS_ERROR_BASE + 3)
#define BB_OSC_INVALID_PKT_LEN			(BB_OSC_CMD_PROSS_ERROR_BASE + 4)
#define BB_OSC_INVALID_CMD_ID			(BB_OSC_CMD_PROSS_ERROR_BASE + 5)

#define BB_OSC_PERIPHERAL_ERROR_BASE	(BB_OSC_FW_ERROR_BASE + 400)
#define BB_OSC_CAPEMGR_FILE_OPEN_FAIL	(BB_OSC_PERIPHERAL_ERROR_BASE + 1)
#define BB_OSC_CAPEMGR_FILE_WRITE_FAIL	(BB_OSC_PERIPHERAL_ERROR_BASE + 2)
#define BB_OSC_CAPEMGR_FILE_READ_FAIL	(BB_OSC_PERIPHERAL_ERROR_BASE + 3)
#define BB_OSC_ADCIIO_FILE_OPEN_FAIL	(BB_OSC_PERIPHERAL_ERROR_BASE + 4)
#define BB_OSC_ADCIIO_FILE_WRITE_FAIL	(BB_OSC_PERIPHERAL_ERROR_BASE + 5)
#define BB_OSC_ADCIIO_FILE_READ_FAIL	(BB_OSC_PERIPHERAL_ERROR_BASE + 6)
#define BB_OSC_INVALID_ADC_ID			(BB_OSC_PERIPHERAL_ERROR_BASE + 7)

int BB_OSC_DisplayErrors(int iErrCode);
#endif
